/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as MonitoringRouteImport } from './routes/monitoring'
import { Route as GraphRouteImport } from './routes/graph'
import { Route as CreditRouteImport } from './routes/credit'
import { Route as AlertsRouteImport } from './routes/alerts'
import { Route as AgentLogRouteImport } from './routes/agent-log'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AlertsIndexRouteImport } from './routes/alerts.index'
import { Route as AlertsIdRouteImport } from './routes/alerts.$id'

const MonitoringRoute = MonitoringRouteImport.update({
  id: '/monitoring',
  path: '/monitoring',
  getParentRoute: () => rootRouteImport,
} as any)
const GraphRoute = GraphRouteImport.update({
  id: '/graph',
  path: '/graph',
  getParentRoute: () => rootRouteImport,
} as any)
const CreditRoute = CreditRouteImport.update({
  id: '/credit',
  path: '/credit',
  getParentRoute: () => rootRouteImport,
} as any)
const AlertsRoute = AlertsRouteImport.update({
  id: '/alerts',
  path: '/alerts',
  getParentRoute: () => rootRouteImport,
} as any)
const AgentLogRoute = AgentLogRouteImport.update({
  id: '/agent-log',
  path: '/agent-log',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AlertsIndexRoute = AlertsIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AlertsRoute,
} as any)
const AlertsIdRoute = AlertsIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => AlertsRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/agent-log': typeof AgentLogRoute
  '/alerts': typeof AlertsRouteWithChildren
  '/credit': typeof CreditRoute
  '/graph': typeof GraphRoute
  '/monitoring': typeof MonitoringRoute
  '/alerts/$id': typeof AlertsIdRoute
  '/alerts/': typeof AlertsIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/agent-log': typeof AgentLogRoute
  '/credit': typeof CreditRoute
  '/graph': typeof GraphRoute
  '/monitoring': typeof MonitoringRoute
  '/alerts/$id': typeof AlertsIdRoute
  '/alerts': typeof AlertsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/agent-log': typeof AgentLogRoute
  '/alerts': typeof AlertsRouteWithChildren
  '/credit': typeof CreditRoute
  '/graph': typeof GraphRoute
  '/monitoring': typeof MonitoringRoute
  '/alerts/$id': typeof AlertsIdRoute
  '/alerts/': typeof AlertsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/agent-log'
    | '/alerts'
    | '/credit'
    | '/graph'
    | '/monitoring'
    | '/alerts/$id'
    | '/alerts/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/agent-log'
    | '/credit'
    | '/graph'
    | '/monitoring'
    | '/alerts/$id'
    | '/alerts'
  id:
    | '__root__'
    | '/'
    | '/agent-log'
    | '/alerts'
    | '/credit'
    | '/graph'
    | '/monitoring'
    | '/alerts/$id'
    | '/alerts/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AgentLogRoute: typeof AgentLogRoute
  AlertsRoute: typeof AlertsRouteWithChildren
  CreditRoute: typeof CreditRoute
  GraphRoute: typeof GraphRoute
  MonitoringRoute: typeof MonitoringRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/monitoring': {
      id: '/monitoring'
      path: '/monitoring'
      fullPath: '/monitoring'
      preLoaderRoute: typeof MonitoringRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/graph': {
      id: '/graph'
      path: '/graph'
      fullPath: '/graph'
      preLoaderRoute: typeof GraphRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/credit': {
      id: '/credit'
      path: '/credit'
      fullPath: '/credit'
      preLoaderRoute: typeof CreditRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/alerts': {
      id: '/alerts'
      path: '/alerts'
      fullPath: '/alerts'
      preLoaderRoute: typeof AlertsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/agent-log': {
      id: '/agent-log'
      path: '/agent-log'
      fullPath: '/agent-log'
      preLoaderRoute: typeof AgentLogRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/alerts/': {
      id: '/alerts/'
      path: '/'
      fullPath: '/alerts/'
      preLoaderRoute: typeof AlertsIndexRouteImport
      parentRoute: typeof AlertsRoute
    }
    '/alerts/$id': {
      id: '/alerts/$id'
      path: '/$id'
      fullPath: '/alerts/$id'
      preLoaderRoute: typeof AlertsIdRouteImport
      parentRoute: typeof AlertsRoute
    }
  }
}

interface AlertsRouteChildren {
  AlertsIdRoute: typeof AlertsIdRoute
  AlertsIndexRoute: typeof AlertsIndexRoute
}

const AlertsRouteChildren: AlertsRouteChildren = {
  AlertsIdRoute: AlertsIdRoute,
  AlertsIndexRoute: AlertsIndexRoute,
}

const AlertsRouteWithChildren =
  AlertsRoute._addFileChildren(AlertsRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AgentLogRoute: AgentLogRoute,
  AlertsRoute: AlertsRouteWithChildren,
  CreditRoute: CreditRoute,
  GraphRoute: GraphRoute,
  MonitoringRoute: MonitoringRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
